name: Release
run-name: Release with new tag ${{ inputs.tag || github.ref }}

on:
  workflow_dispatch:
    inputs:
        tag:
          description: 'Manual release tag'
          required: true
          type: string
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile
       
      - name: Build assets
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ inputs.tag || github.ref_name }}-${{ github.run_id }}
          overwrite: true
          include-hidden-files: true
          path: |
            ./
            !./.*
            !./*.js
            !./READ*
            !./[jp]*.json
            !./phpu*
            !./yarn*
            !.github/
            !.git/
            !./database/factories/
            !./storage/debugbar/
            !./tests/
            !./node_modules/
            !./vendor/
            !./resources/js/
            !./resources/css/
       
