name: Release

on:
  workflow_dispatch:
    inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tag:
          description: 'Manual release tag'
          required: true
          type: string
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      
    steps:
           
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v3
        
      - name: Build assets
        run: yarn build

      - name: Print
        run: |
            echo "Tag: $TAG"
            echo "Dir: $(pwd)"
            tree public/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ inputs.tag || github.ref }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-vendor
          path: |
            .
            !.github
            !vendor
       
